
#' SeqANOVA
#'
#' This function performs Analysis of variance (ANOVA) on SeqDataframe() format dataframes and returns a P-value. Groups are selected automatically based on name e.g. group1_0, group1_1, group1_2, group2_0, group2_1, group2_2,group3_0, group3_1, group3_2 would perform ANOVA on group1, group2, and group3. Returns p-value (anova.p) and adjusted p-vale (anova.p.adj)
#' @param df The dataframe generated by SeqDataframe
#' @param p.adjust.method Correction method for ANOVA p-value. Accepted options are "holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr", "none". See ?p.adjust for discussion of methods. Default = "bonferroni"
#' @return dataframe containing FPKM values and ANOVA p-value and adjusted ANOVA p-value for all groups.
#' @export
#' @examples
#' results <- SeqANOVA(SeqDataframe(dir="./norm_out"))
#' 
SeqANOVA <- function(df = df,
                     p.adjust.method = "bonferroni",
                     ...){
    
    library(matrixStats)
    
    ## Get the unique group names
    ## Column names to exclude
    exclude <- "gene|.p|Mean.|log2."
    group_names <- function(df){
        names <- unique(gsub("\\_[0-9]*$", "",colnames(df)[grep(exclude, colnames(df),invert = TRUE)]))
        return(names)
    }
    
    ## Get the total samples, N
    get_n <- function(df){
        n <- length(unique(colnames(df)[grep(exclude, colnames(df),invert = TRUE)]))
        return(n)
    }

    ## make matrices for each experimental condition
    get_matrices <- function(df){

        get_groups <- function(df){
            list <- lapply(group_names(df),
                           function(x) {intersect(
                                            grep(x, colnames(df)),
                                            grep(exclude, colnames(df),invert = TRUE))})
            list[[length(list)+1]] <- grep(exclude, colnames(df),invert = TRUE)
            return(list)
            }
        
        x <- get_groups(df)
        matrices <- sapply(x, function(x){df[,x]})
        return(matrices)
    }
    
    ## Exclude last matrix
    mats <- get_matrices(df)[-length(get_matrices(df))]
    
    #############################################################################
    ## parallel implementation (SLOWER)                                        ##
    ## library(parallel)                                                       ##
    ## c <- makePSOCKcluster(detectCores())                                    ##
    ## sst.1 <- parLapply(cl = c,                                              ##
    ##                    mats, function(mats){rowSums((mats), na.rm = TRUE)}) ##
    ## stopCluster(c)                                                          ##
    #############################################################################
    
    ## calculate sum of squares for all matrices
    make_sst <- function(n){        
        x <- lapply(mats,
                    function(mats){rowSums((mats^n), na.rm = TRUE)})
        x <- data.frame(matrix(unlist(x),
                               nrow = unique(sapply(x, length)),
                               byrow = FALSE))
        return(x)
    }

    ## calculate total sum of squares for each row
    get_sst <- function(sst.1,sst.2, df){
        sst <- rowSums(sst.2) - (rowSums(sst.1)^2)/get_n(df)
        return(sst)
    }
    
    sst <- get_sst(make_sst(1),make_sst(2), df)

    ## sum of squares among, by row
    ssa <- rowSums((make_sst(1)^2)/unlist(lapply(mats, function(x) length(x)))) -  (rowSums(make_sst(1))^2)/get_n(df)

    ## sum of squares within
    ssw <- sst - ssa
    ## calculate fstat
    fstat <- (ssa/(length(mats)-1))/(ssw/(get_n(df)-length(mats)))
    ## express f-statistic as p-value
    df$anova.p <- pf(q = fstat,
                     df1 = length(mats)-1,
                     df2 = (get_n(df)-length(mats)), lower.tail = FALSE)
    ## multiple testing corrections
    df$anova.p.adj <- p.adjust(df$anova.p,
                               method = p.adjust.method,
                               n = length(df$anova.p))
    return(df)
}
## Sources for ANOVA formula
## https://people.richland.edu/james/lecture/m170/ch13-1wy.html
## http://web.mst.edu/~psyworld/anovaexample.htm
