#' SeqStatSubset
#'
#' This function subsets a SeqDataframe according to the results of a two-tailed unpaired Student's t-test and returns a dataframe containing only the genes and FPKM values meeting the statistical significance criteria
#'
#' @param data The dataframe generated by SeqDataframe
#' @param group1 A string unique to the columns in 'data' that contain the first data set to be compared
#' @param group2 A string unique to the columns in 'data' that contain the second data set to be compared
#' @param limit A value representing the threshold of statistical significance, or maximum P-value considered to represent a significant difference. Default is set at 0.05.
#' @param Bonferroni A boolean operator to determine the use of Bonferroni correction when subsetting based on P-value. Default is FALSE, meaning that no Bonferroni correction is performed.
#' @export
#' @examples
#' data <- SeqDataframe(dir="./norm_out")
#' subset <- SeqStatSubset(data, limit= 0.001, group1 = "ES", group2 = "HLO")

SeqStatSubset <- function(data,
                          limit = 0.05,
                          Bonferroni = FALSE,
                          group1 = "HLO",
                          group2 = "ES"){
    # calculate stats using SeqRetriever::SeqStudents()
    df <- SeqStudents(data, group1 = group1, group2 = group2)
    # Dteremint which set of p-values based on user Bonferroni specification
    if (Bonferroni == FALSE) {
        df <- subset(df, df$p <= limit)
    } else {
        df <- subset(df, df$Bonf_p <= limit)
    }
    # Find genes in the significant subset that match input
    match <- which(data$gene_short_name %in% df$gene_short_name)
    # Limit input to matches with significant subset
    data <- data[match,]
    return(data)
}
