#' SeqStatSubset
#'
#' This function subsets a SeqDataframe according to the results of a two-tailed unpaired Student's t-test and returns a dataframe containing only the genes and FPKM values meeting the statistical significance criteria
#'
#' @param df The dataframe generated by SeqDataframe
#' @param group1 A string unique to the columns in 'data' that contain the first data set to be compared
#' @param group2 A string unique to the columns in 'data' that contain the second data set to be compared
#' @param limit A value representing the threshold of statistical significance, or maximum P-value considered to represent a significant difference. Default is set at 0.05.
#' @param p.adjust Boolean operator to determine the use of multiple testing correction correction when subsetting based on P-value. Default is FALSE, meaning that no multiple testing correction is performed.
#' @param p.adjust.method Multiple testing correction method for  p-value. Accepted options are "holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr", "none". See ?p.adjust for discussion of methods. Default = "bonferroni"
#' @param method Statistical test to be performed. Accepted options are "t.test" and "anova". Option "t.test' requires specification of group1 and group2; these variables are ignored if "anova" is selected. Default = "t.test"
#' @export
#' @examples
#' data <- SeqDataframe(dir="./norm_out")
#' subset <- SeqStatSubset(data, limit= 0.001, group1 = "ES", group2 = "HLO")

SeqStatSubset <- function(df = df,
                          method = "t.test",
                          limit = 0.05,
                          p.adjust = FALSE,
                          p.adjust.method = "bonferroni",
                          group1 = "HLO",
                          group2 = "ES"){

    ## Strip out all summary test columns and statistical tests
    strip_stats <- function(x){
        o <- x[,grep(".p|Mean.|log2.", colnames(df),invert = TRUE)]
        return(o)
    }
    
    ## Function to determine SeqStatSubset method
    f <- function(method){
        wrong.input <- "Error: method must be 't.test' or 'anova'"
        x <- if(method == "t.test") {
                 x <- SeqStudents
             } else if(method == "anova") {
                 x <- SeqANOVA
             } else {
                 x <- function(...) {print(wrong.input)}
             }
         return(x)
     }
    ## Set SeqStatSubset method
    f <- f(method)

    ## calculate stats using user specified method
    d <- f(df = strip_stats(df),
           group1 = group1,
           group2 = group2,
           p.adjust.method = p.adjust.method)
    
    ## Find columns with standard and adjusted p-values
    std <- intersect(
        grep(".p", colnames(d)),
        grep(".adj", colnames(d),invert = TRUE))
    adj <- grep(".adj", colnames(d))
    
    ## subset function based on submitted column index
    s4 <- function(x) {
        s <- subset(d, d[,x] <= limit)
        return(s)
    }
    
    if (p.adjust == FALSE) {
        d <- s4(std)
     } else {
        d <- s4(adj)
    }

    ## Find genes in the significant subset that match input
    match <- which(df$gene_short_name %in% d$gene_short_name)
    
    ## Limit input to matches with significant subset & remove stats
    d <- strip_stats(df[match,])
    
    return(d)
}

