
#' SeqStudents
#'
#' This function performs a two-tailed Student's t-test on two groups specified by the user. The preferred input is a dataframe generated using SeqDataframe().
#' @param data The dataframe generated by SeqDataframe
#' @param group1 A string unique to the columns in 'data' that contain the first data set to be compared
#' @param group2 A string unique to the columns in 'data' that contain the second data set to be compared
#' @export
#' @examples
#' results <- SeqStudents(SeqDataframe(dir="./norm_out"), group1 = "ES", group2 = "HLO")

SeqStudents <- function(data,
                        group1 = "ES",
                        group2 = "HLO"){
    
    # Define the two sample groups
    gp1 <- grep(group1,colnames(data))
    gp2 <- grep(group2,colnames(data))
    # Calculate mean by sample group
    library(matrixStats)
    data[paste("Mean_",group1,sep="")] <- rowMeans(data[,gp1],na.rm=T)
    data[paste("Mean_",group2,sep="")] <- rowMeans(data[,gp2],na.rm=T)
    # Calculate log2 expression 
    data[paste("log2_",group1,"_ovr_",group2,sep="")] <- log2(data[paste("Mean_",group1,sep="")]/data[paste("Mean_",group2,sep="")])
    ## function to compare by row, returns t distribution
    ## The function is defined as
    row.t <- function(mat1,mat2){
        mat1 <- as.matrix(mat1)
        mat2 <- as.matrix(mat2)
        n1 <- dim(mat1)[2]
        n2 <- dim(mat2)[2] 
        n <- n1+n2 
        m1 <- rowMeans(mat1,na.rm=TRUE) 
        m2 <- rowMeans(mat2,na.rm=TRUE) 
        v1 <- rowVars(mat1,na.rm=TRUE) 
        v2 <- rowVars(mat2,na.rm=TRUE) 
        vpool <- (n1-1)/(n-2)*v1 + (n2-1)/(n-2)*v2 
        tstat <- sqrt(n1*n2/n)*(m1-m2)/sqrt(vpool) 
        return(tstat)
    }
    # calculate t-distribution for group1 vs. group2
    data$tstat <- row.t(data[,gp1],data[,gp2])
    # calculate degrees of freedom
    degfree <- (length(gp1)+length(gp2))-2
    # express t-dist as two-sided p-value
    data$p <- 2*pt(-abs(data$tstat),df=degfree)
    # calculate Bonferroni correction
    data$Bonf_p <- p.adjust(data$p, method = 'bonferroni', n = length(data$p))
    # sort based on p-value
#    data <- data[order(data$p),]
    return(data)
}
