
#' SeqStatSubset
#'
#' This function subsets a SeqDataframe according to the results of a two-tailed unpaired Student's t-test and returns a dataframe containing only the genes and FPKM values meeting the statistical significance criteria
#'
#' @param data The dataframe generated by SeqDataframe
#' @param group1 A string unique to the columns in 'data' that contain the first data set to be compared
#' @param group2 A string unique to the columns in 'data' that contain the second data set to be compared
#' @param limit A value representing the threshold of statistical significance, or maximum P-value considered to represent a significant difference. Default is set at 0.05.
#' @param Bonferroni A boolean operator to determine the use of Bonferroni correction when subsetting based on P-value. Default is FALSE, meaning that no Bonferroni correction is performed.
#' @export
#' @examples
#' data <- SeqDataframe(dir="./norm_out")
#' subset <- SeqStatSubset(data, limit= 0.001, group1 = "ES", group2 = "HLO")

SeqStatSubset <- function(data,
                          limit = 0.05,
                          Bonferroni = FALSE,
                          group1 = "HLO",
                          group2 = "ES"){
    # calculate stats using SeqRetriever::SeqStudents()
    df <- SeqStudents(data, group1 = group1, group2 = group2)
    # Dteremint which set of p-values based on user Bonferroni specification
    if (Bonferroni == FALSE) {
        df <- subset(df, df$p <= limit)
    } else {
        df <- subset(df, df$Bonf_p <= limit)
    }
    # Find genes in the significant subset that match input
    match <- which(data$gene_short_name %in% df$gene_short_name)
    # Limit input to matches with significant subset
    data <- data[match,]
    return(data)
}

#' SeqHeatmap
#'
#' This function searches cuffnorm format gene expression data for user specified genes and generates a heatmap with hierarchical clustering.
#' @param hm.name Name of heatmap output. Default is "gr_heatmap.pdf"
#' @param cellwidth Heatmap cell width in px. Default 30
#' @param cellheight Heatmap cell height in px. Default 30
#' @return Normalized FPKM matrix containing the specified subset of genes accross all samples. Additional options will plot expression of individual genes as box plots and/or a heatmap with hierarchical clustering
#' @export
#' @examples
#' getSRexample() # Downloads and unpacks example dataset in working directory
#' data <- SeqDataframe(dir="./norm_out")
#' SeqHeatmap(data)

SeqHeatmap <- function(df,
                       hm.name = "SRheatmap.png",
                       w = 8,
                       h = 11,
                       cellwidth = 15,
                       cellheight = 15)

{
    ## Need matrix. Remove non-numeric
    # Test is numeric
    num <- sapply(df, is.numeric)
    # Subset to TRUE columns
    data.sub.sum.num <- df[,num]
      # Subset to rows where SD != 0, ingnoring NA values
    hm.df <- data.sub.sum.num[apply(data.sub.sum.num, 1, sd, na.rm = TRUE) != 0,]
      ## Begin heatmap plotting
      # Notify user
    print(paste("Generating heatmap and saving as", hm.name))  
      # Open PNG device
    png(file = hm.name, width=w, height=h, units="in", res=144)
    library(pheatmap)
    library(RColorBrewer)
    pheatmap(hm.df,
             scale = "row",
             clustering_method = "average",
             color=colorRampPalette(rev(brewer.pal(n=7, name="RdYlBu")))(300),
             main = "",
             border_color = "black",
             cellwidth = cellwidth,
             cellheight = cellheight,
             show_rownames = TRUE,
             fontsize = 12,
             filename = hm.name)
}
